name: Run codegen
description: Run codegen
runs:
  using: composite
  steps:
    - name: Setup Rust toolchain
      uses: ./.github/actions/setup-rust-toolchain
    - name: Check new version
      id: check-new-version
      uses: EndBug/version-check@d4be4219408b50d1bbbfd350a47cbcb126878692 # v2.1.4
      with:
        file-name: ./biome/packages/@biomejs/biome/package.json
        static-checking: localIsNew
    - name: Codegen rules
      if: ${{ steps.check-new-version.outputs.changed == 'false' }}
      shell: bash
      run: cargo run --manifest-path codegen/Cargo.toml rules
      env:
        RUST_LOG: info
        RUST_BACKTRACE: "1"
        CARGO_INCREMENTAL: "1"
    - name: Codegen all
      if: ${{ steps.check-new-version.outputs.changed == 'true' }}
      shell: bash
      run: cargo run --manifest-path codegen/Cargo.toml all
      env:
        RUST_LOG: info
        RUST_BACKTRACE: "1"
        CARGO_INCREMENTAL: "1"
        BIOME_VERSION: ${{ steps.check-new-version.outputs.version }}
